#!/bin/bash
set -e
### BEGIN INIT INFO
# Provides:          pandora-bootparam
# Required-Start:
# Required-Stop:        umountroot
# Should-Start:
# Should-Stop:          halt reboot
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description: Open Parrot Pandora's box and clean the RAM.
### END INIT INFO

#
# Lorenzo "EclipseSpark" Faletra <eclipse@frozenbox.org>
#         Parrot Security OS www.parrotsec.org
#                      GNU/GPL v3
# Extended:
# RJMVisser <https://github.com/RJMVisser>

export RED='\033[1;91m'
export RESETCOLOR='\033[1;00m'

function rootcheck {
    # Make sure only root can run this script
    ME=$(whoami | tr "[:lower:]" "[:upper:]")
    if [ "$(id -u)" -ne 0 ]; then
        echo -e "\n[${RED}!$RESETCOLOR] $RED $ME R U DRUNK?? This script must be run as root$RESETCOLOR\n" >&2
        exit 1
    fi
}

function bomb {
    rootcheck
    mkdir -p /etc/pandora/
    if [ ! -f /etc/pandora/min_free_kbytes ] 
    then
        cat /proc/sys/vm/min_free_kbytes > /etc/pandora/min_free_kbytes
    fi
    echo "Pandora is dropping caches"
    echo 1024 > /proc/sys/vm/min_free_kbytes
    echo 3  > /proc/sys/vm/drop_caches
    echo 1  > /proc/sys/vm/oom_kill_allocating_task
    echo 1  > /proc/sys/vm/overcommit_memory
    echo 0  > /proc/sys/vm/oom_dump_tasks
    echo "Pandora is bombing RAM"
    semem -fll
    echo " - RAM bombed"
    echo "closing Parrot Pandora's box"
}

function restore {
    rootcheck
    echo "Restore minimum free cache size to original"
    if [ -f /etc/pandora/min_free_kbytes ]
    then
        cat /etc/pandora/min_free_kbytes > /proc/sys/vm/min_free_kbytes
        rm /etc/pandora/min_free_kbytes
    fi
}


case "$1" in
    bomb)
        bomb
        ;;
    restore)
        restore
        ;;
    *)
        echo "Usage: "
        echo "pandora { bomb | restore }"
esac
